<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/public/css/style.css">
    <title><?php echo $this->page_title; ?></title>
</head>
<body>
    <div class="container">
        <div class="transparent-container">
            <h1 class="text-center">Darāmo lietu saraksts</h1>