<h2 class="text-center">Labot</h2>

<form method="POST">
    <input type="hidden" name="token" value="<?php echo $this->view_data['token']; ?>">
    <div class="form-group">
        <label for="title-edit">Virsraksts:</label>
        <input type="text" class="form-control" id="title-edit" name="title"
               value="<?php echo $this->view_data['title']; ?>" maxlength="100" required>
    </div>
    <div class="form-group">
        <label for="description-edit">Apraksts:</label>
        <textarea class="form-control" id="description-edit" name="description"
                  rows="4" maxlength="500"><?php echo $this->view_data['description']; ?></textarea>
    </div>
    <input type="submit" class="btn btn-success" id="save" name="save_btn" value="Saglabāt">
    <input type="submit" class="btn btn-danger" id="delete" name="delete_btn" value="Dzēst">
    <a href="/public/all_tasks" class="back btn btn-secondary">Doties atpakaļ</a>
</form>